---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: blast
    run_list:
      - recipe[blast::default]
    attributes:
  - name: blast2
    run_list:
      - recipe[blast::default]
    attributes:
      blast:
        version: '2.4.0'
    excludes: centos-7.2
