sudo: required
dist: trusty

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk

install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  global:
  - RUBYOPT="-W0"
  matrix:
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
  - CHEF_VERSION=current INSTANCE=default-centos-72

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- "/opt/chefdk/bin/chef exec rake tests"

script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

notifications:
  slack:
    secure: GatT/vs6Rxp7pKcKHYLH957yhQxZJXGHz/bSN2GjJuVWPq2ut9JDKYLpuRxU7OSCwV7hDTe7pmw0wM/X0WkMAd7BLqQWDfLh+m75aJ4chSdb2OtQ9dsaI+rnCRiEJrJt08NTBBkdp4XEskzj6A64kGyBYy0J55Zc7EU3WfHoFQeFffLtJIB4bb0umt4N0Z60e6I7oooab0ONgpGrLK613LLsg3HSOf4UYmW+5gDGRwDSJjWAXlrAf1XSHKcAT1WFU9ZGcm1Kwe1LEEZw+X4lg4tXaHU06ccWpXDmBcfEgI+x29Ax2jjLk6uBlxYB7O/SQbaOd4qv4gNfCnJiKCBVtXVChS4hTw5j3k5XsbRupJ43w/3/eHgai2hzYyNKhr2beTV7QZ0yNnpDd/FIcznO+c4W5m7mDnUBumQe8tACAlFP4F8Fiurbz0zDmyjQ6L8hWp+PWH5RnIRK67Dp15MAj8+Fv3fC4QRQIsF3NnWFN28eJAGI8nesgu8EjNivORiyz08kWfH/z1TmCCDkzUkhFa4WlS0qJjRCiWLZuxAqYxC0MDAxpYdWzn7mfaTLPaS/1ma+rhBAvR2+12tWLRmTv3PF3m+VHB4R9wVyV6tfW/Z61+TP2oYwUhbX+M02v8z1LXdFQLvHbVfrYr2Uo4gFP3PzwKWcxiP783Z96hqpoC8=
    on_failure: change
    on_success: change
  email:
    on_success: change
    on_failure: always
