name 'blast'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apachev2'
description 'Installs/Configures BLAST'
long_description 'Installs/Configures BLAST'
source_url 'https://github.com/EagleGenomics-cookbooks/blast'
issues_url 'https://github.com/EagleGenomics-cookbooks/blast/issues'
version '1.0.2'

depends 'build-essential'
depends 'apt'
