name 'BLAST'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apachev2'
description 'Installs/Configures BLAST'
long_description 'Installs/Configures BLAST'
version '0.1.0'
